version: "3.9"

services:
  php:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: atlas-php
    working_dir: /var/www/html
    volumes:
      - ./api:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    depends_on:
      - db
      - redis
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
      - PHP_IDE_CONFIG=serverName=atlas
    networks:
      - atlas-network

  web:
    image: nginx:1.27-alpine
    container_name: atlas-web
    ports:
      - "8081:80"
    volumes:
      - ./api:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - atlas-network

  node:
    image: node:20-alpine
    container_name: atlas-node
    working_dir: /app
    volumes:
      - ./app:/app
      - /app/node_modules
    command: sh -lc "npm install && npm run dev"
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    networks:
      - atlas-network

  db:
    image: pgvector/pgvector:pg16
    container_name: atlas-db
    environment:
      POSTGRES_DB: atlas
      POSTGRES_USER: atlas
      POSTGRES_PASSWORD: atlas
    ports:
      - "5433:5432"
    volumes:
      - atlas-db:/var/lib/postgresql/data
    networks:
      - atlas-network

  redis:
    image: redis:7-alpine
    container_name: atlas-redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - atlas-network

  meili:
    image: getmeili/meilisearch:v1.8
    container_name: atlas-meili
    ports:
      - "7700:7700"
    environment:
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: "masterKey"
    volumes:
      - atlas-meili:/meili_data
    networks:
      - atlas-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: atlas-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - atlas-network

volumes:
  atlas-db:
  atlas-meili:

networks:
  atlas-network:
    driver: bridge
